chore: setup eslint
sse-js/client-kit pull request #10
Opened 2022-11-19 19:23 UTC by Xstoudi

2022-11-19 20:16 UTC, Purexo requested changes

2022-11-19 20:16 UTC, Purexo commented on src/undici/EventSource.ts
> +      .catch(this.signalError);
signalError n'est pas une arrow function donc le context est perdu utilisé comme ca

2022-11-19 20:16 UTC, Purexo commented on package.json
> -    "bracketSpacing": false,
J'aime bien avec (compact) mais ça ce négocie ^^

2022-11-19 20:16 UTC, Purexo commented on src/eventStreamParser.ts
> +    let value: IteratorResult<string> = { done: false, value: '' };
Je préfère le typing literal quand possible plutôt que Generic

2022-11-19 20:16 UTC, Purexo commented on src/eventStreamParser.ts
> +    function next(): boolean | undefined {
A quel moment un iterateur retourne done undefined plutôt que true ou false ?

2022-11-19 20:16 UTC, Purexo commented on src/eventStreamParser.ts
> +    while (!(next() ?? true)) {
Dans la possibilité improbable ou l'intérateur retourne null/undefined plutôt que true ou false, la défaut value doit être false, pas true

2022-11-19 20:31 UTC, Xstoudi commented on package.json
> -    "bracketSpacing": false,
Si on préfère le compact on dégage les `;` keepo

2022-11-19 20:42 UTC, Purexo commented on package.json
> -    "bracketSpacing": false,
Je suis un être de contradiction ! Aller, va pour le bracketSpacing ^^

2022-11-19 20:46 UTC, Xstoudi commented on src/eventStreamParser.ts
> +    function next(): boolean | undefined {
![MeXElAbo09](https://user-images.githubusercontent.com/2575182/202871015-9bf21ec0-2bab-448c-83b0-8a008636a49b.png)
Y a une singerie quelque part.

2022-11-19 20:54 UTC, Purexo commented on src/eventStreamParser.ts
> +            if (event.comments == null) {
J'avais oublié un comment ici, tu veux vraiment garder des looseEq null plutôt qu'un check falsy ?
Je trouve ça chelou dans le sens que ça n'est jamais init null, au pire c'est undefined car la clé n'est pas encore dans l'objet

2022-11-20 08:27 UTC, Purexo approved these changes

2022-11-20 08:29 UTC, merged

2022-11-20 08:31 UTC, Purexo commented
https://github.com/Purexo/EventStream/issues/2